### ISSUE TITLE
Consider relicensing under more standard license

### ISSUE THREAD

**Issue by mikz** [jonstoler/lua-toml#15]
Hi, thanks for a great library.

I'd like to use this project for configuration file of http://github.com/3scale/apicast.
The Happy License sounds nice, but would be easier to rely on something more standard like the MIT License. 

>  subject to the licensee inflecting a positive message 
unto someone. This includes (but is not limited to): smiling, being nice, 
saying "thank you", assisting other persons, or any similar actions percolating 
the given concept.

Is quite debatable in my opinion and won't pass a corporate legal team.

**Comment by jonstoler** [comment]
Yes, I agree. I chose that license years ago before I knew much about licensing. This is something I've wanted to change but haven't tried to do it until someone asked. I'm just unsure what the standard procedure for changing license terms is.

If you have any advice or tips, let me know. I've wanted to do this but I'm unsure how.

**Comment by mikz** [comment]
Thank you. 

I've seen https://github.com/Safari-FIDO-U2F/Safari-FIDO-U2F/issues/20 recently.
I'd say that you are the only major contributor. Other changes have been trivial.

So it should be just matter of changing the license and maybe updating rockspec to mention the new license.

**Comment by jonstoler** [comment]
Fixed in 75d30d2.

I'm considering this a "breaking API change" so I bumped up to version 2.0.0. It's not exactly an API change, but it *is* potentially breaking in the rare case that MIT doesn't fit someone's needs but the old license does.

**Comment by mikz** [comment]
Thank you so much for such quick response!
