### ISSUE TITLE
Some japanese characters detected as "newline" during parse

### ISSUE THREAD

**Issue by tomoe-mami** [jonstoler/lua-toml#16]
Using the following TOML string:

```toml
"Lucky Dragon No. 5" = "第五福龍丸"
"Subterranean Animism" = "東方地霊殿" 
```

toml.parse produced error:

```
TOML: Single-line string cannot contain line break on line 3.
```

If I remove the last line, it parses correctly.

**Comment by jonstoler** [comment]
This fix brings to light #17, which was always a bug, but until now was an unknown bug.
