### ISSUE TITLE
TOML v0.4.0

### ISSUE THREAD

**Issue by jonstoler** [jonstoler/lua-toml#2]
[TOML v0.4.0](https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.4.0.md) was released in February.

lua-toml should be updated to support it.

**Comment by mepholic** [comment]
I'd be willing to write some of this. I will get more familiar with the internals of lua-toml in my free time and attempt to implement some of the required checks and features.

**Comment by jonstoler** [comment]
Cool, I'd appreciate your help!

This is pretty high on my priority list but I've been busy with school so haven't had time to tackle it. I was hoping to make sure we can pass all tests (see #1) first. Currently I'm using [https://github.com/BurntSushi/toml-test](BurntSushi/toml-test) as a base, and lua-toml passes most tests but has failed a few bizarre edge cases, like where a table key is made up of symbols rather than letters and numbers. Still, I'd love to be able to pass these cases as well.

I should have more time in about a month or so, and would be happy to work together to tackle both of these standing problems.

**Comment by jonstoler** [comment]
Okay, 0.4.0 officially supported!
