### ISSUE TITLE
Strictness is set globally

### ISSUE THREAD

**Issue by Lukc** [jonstoler/lua-toml#5]
If a module or library uses lua-toml and changes its strictness configuration (`TOML.strict = false`), that change will also affect all the calling applications.

IMHO, adding a parameter to `TOML.parse` to set that particular setting would be much better in that regard.

**Comment by jonstoler** [comment]
Fixed.

Now `TOML.parse` can optionally be given a table of settings, which override global settings. You can still use global settings if you want, as long as you don't specify a table of settings when calling `TOML.parse`.

Right now, the only setting is `strict`, but I've chosen to use a table of options for future flexibility.
