### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by mepholic** [jonstoler/lua-toml#9]
I'm currently working on writing some LDoc documentation for the library and it's internals.

@jonstoler I have a couple questions, what's the best way for me to contact you?

**Comment by jonstoler** [comment]
@mepholic Feel free to email me at jrsgithub@stoler.com with any questions!

**Comment by jonstoler** [comment]
Ok, just added comments all over the place. Hopefully it clears things up at least a little?

Feel free to add more if you'd like.
